apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: helse-spydig
  namespace: tbd
  labels:
    team: tbd
spec:
  route:
    group_by: [ slack_channel ]
  receivers: # receivers for all alerts below
    slack:
      channel: '{{ index ((index .Alerts 0).Labels) "slack_channel" }}'
      icon_emoji: ':horse_racing:'
      send_resolved: false
      username: Spydig
  alerts:
    - alert: test
      expr: 'increase(spydig_validation_errors_total[5m]) > 0'
      for: 1s
      description: |
        Validering av json schema oppdaget feil.
        Kilde: "{{ $labels.failing_app }}".
      action: ""