apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: helse-spydig
  namespace: tbd
  labels:
    team: tbd
spec:
  receivers: # receivers for all alerts below
    slack:
      channel: '{{ $labels.slack_channel }}'
      icon_emoji: ':horse_racing:'
      send_resolved: false
      username: Spydig
  alerts:
    - alert: test
      expr: 'increase(spydig_test_total[5m]) > 0'
      for: 1s
      description: |
        Endepunkt åpnet, sender melding i "{{ $labels.slack_channel }}".
      action: |
        Resultat av expr skal være:
        "{{ index ((index .Alerts 0).Labels) "slack_channel" }}"
  
