apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: helse-spydig
  namespace: tbd
  labels:
    team: tbd
spec:
  receivers: # receivers for all alerts below
    slack:
      channel: '\{{ index ((index .Alerts 0).Labels) "slack_channel" }}'
      prependText: '<!here> | ' # this text will be prepended to the Slack alert title
  alerts:
    - alert: schema validering feilet
      expr: 'increase(spydig_validation_errors_total[1m]) > 0'
      for: 1s
      description: "validering av schema feilet"
      action: "spis en kanelbolle"
    - alert: schema validering feilet spleis
      expr: 'spydig_validation_errors_spleis_total > 0'
      for: 1s
      description: "validering av schema feilet for spleis"
      action: "spis en kanelbolle SPLEIS"
    - alert: test
      expr: 'increase(spydig_test_total[5m]) > 0'
      for: 1s
      description: |
        Validering av json schema feilet "\{{ $labels.kilde }}".
        '\{{ index ((index .Alerts 0).Labels) "slack_channel" }}'
      action: |
        spis en kanelbolle "\{{ $labels.ny_label_2 }}".
  
