apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: helse-spydig
  namespace: tbd
  labels:
    team: tbd
spec:
  service:
    protocol: http
  ingresses:
    - https://helse-spydig.dev.intern.nav.no
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    initialDelay: 30
    path: isalive
  readiness:
    initialDelay: 30
    path: isready
  replicas:
    max: 1
    min: 1
  kafka:
    pool: nav-dev
  prometheus:
    enabled: true
    path: /metrics
  env:
    - name: SUBSUMSJON_TOPIC
      value: "flex.omrade-helse-etterlevelse"