apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: spydig-alert
  namespace: tbd
  labels:
    team: tbd
spec:
  route:
    group_by: [ slack_channel ]
  receivers: # receivers for all alerts below
    slack:
      channel: '{{ index ((index .Alerts 0).Labels) "slack_channel" }}'
      icon_emoji: ':paragrafrytterne:'
      send_resolved: false
      username: Spydig
  alerts:
    - alert: Feil ved validering av subsumsjonsmeldinger
      expr: 'increase(spydig_validation_errors_total[5m]) > 0'
      for: 1s
      description: |
        Hei, vi fant problemer vedrørende en subsumsjonsmelding
        fra applikasjonen: {{ $labels.failing_app }}.
      action: |
        1. gå til https://logs.adeo.no/goto/717ba320-fc64-11ec-a503-d3f90a22c586 for å se hva som er feil
        2. gå til tjenestekalloggen for å se hele meldingen 
        3. oppdater appen slik at subsumsjonsmeldingene matcher schema som du finner her:
        https://github.com/navikt/helse/tree/main/subsumsjon
