apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spydig
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    path: isalive
  readiness:
    path: isready
  replicas:
    max: 1
    min: 1
  accessPolicy:
    outbound:
      external:
        - host: raw.githubusercontent.com
  kafka:
    pool: {{kafka-pool}}
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  env:
    - name: SUBSUMSJON_TOPIC
      value: "flex.omrade-helse-etterlevelse"
